language: php

sudo: true

php:
- 5.6
- 7.1
- 7.2

services:
- sqlite
- docker

before_install:
  - docker run -d -p 6379:6379 redislabs/redisearch:latest --protected-mode no --loadmodule /usr/lib/redis/modules/redisearch.so

before_script:
- composer install
- travis_retry composer self-update
- travis_retry composer update --no-interaction --prefer-dist
- composer show laravel/framework

script:
- vendor/bin/phpunit
