language: php

sudo: true

php:
- 7.1
- 7.2
- 7.3
- 7.4

services:
- sqlite

before_script:
- composer install
- travis_retry composer self-update
- travis_retry composer update --no-interaction --prefer-dist
- composer show laravel/framework
- composer dump-autoload

script:
- vendor/bin/phpunit
